// Predefined scenarios still get a curated union for editor autocomplete,
// but ScenarioId itself is a plain string so that user-requested/generated
// scenarios (e.g. "job interview") can be used without hardcoding every name.
export type PredefinedScenarioId =
    | 'greetings'
    | 'restaurant'
    | 'shop'
    | 'plane'
    | 'airport'
    | 'hotel';

export type ScenarioId = string;

export interface ScenarioMeta {
    id: ScenarioId;
    label: string;
    description: string;
}

export interface Phrase {
    id: string;
    /** Scenario/topic this phrase belongs to, used to group a conversation flow */
    scenario: ScenarioId;
    /** 1-based position of this phrase within its scenario's conversation flow */
    order: number;
    japanese: string;
    romaji: string;
    english: string;
    audioUrl: string;
    difficulty: 'beginner' | 'intermediate' | 'advanced';
    /**
     * 'phrase' (default): shows japanese/romaji/english as a phrase someone
     * else says, then practicePrompt asks the user to respond to it.
     * 'translate': shows practicePrompt (e.g. "How do you say '...'?") as the
     * question itself, with exampleResponse/exampleResponseJapanese as the answer.
     */
    promptType?: 'phrase' | 'translate';
    practicePrompt: string;
    /** A correct example response (romaji) used to generate hints */
    exampleResponse: string;
    /** The same example response written in Japanese script (katakana/hiragana/kanji) */
    exampleResponseJapanese: string;
    /**
     * Additional acceptable answers besides exampleResponse/exampleResponseJapanese
     * (up to 2 more, so 3 total). Any of them is marked correct when submitted.
     */
    alternateAnswers?: {
        exampleResponse: string;
        exampleResponseJapanese: string;
    }[];
    /** Whether this phrase was hand-written or generated by an LLM */
    source?: 'seed' | 'generated';
    /** ISO timestamp of when a generated phrase was created */
    generatedAt?: string;
}

export interface PracticeResponseEntry {
    text: string;
    submittedAt: string;
}
