// Predefined scenarios still get a curated union for editor autocomplete,
// but ScenarioId itself is a plain string so that user-requested/generated
// scenarios (e.g. "job interview") can be used without hardcoding every name.
export type PredefinedScenarioId =
    | 'greetings'
    | 'restaurant'
    | 'shop'
    | 'plane'
    | 'airport'
    | 'hotel';

export type ScenarioId = string;

export interface ScenarioMeta {
    id: ScenarioId;
    label: string;
    description: string;
}

export interface Phrase {
    id: string;
    /** Scenario/topic this phrase belongs to, used to group a conversation flow */
    scenario: ScenarioId;
    /** 1-based position of this phrase within its scenario's conversation flow */
    order: number;
    japanese: string;
    romaji: string;
    english: string;
    audioUrl: string;
    difficulty: 'beginner' | 'intermediate' | 'advanced';
    practicePrompt: string;
    /** A correct example response (romaji) used to generate hints */
    exampleResponse: string;
    /** Whether this phrase was hand-written or generated by an LLM */
    source?: 'seed' | 'generated';
    /** ISO timestamp of when a generated phrase was created */
    generatedAt?: string;
}

export interface PracticeResponseEntry {
    text: string;
    submittedAt: string;
}
